local M = {}

-- JetBrains Hacker (Specktro) palette reference for manual edits.
local P = {
  ui_bg = "#000000",
  ui_fg = "#FFFFFF",
  editor_bg = "#1F1F1F",
  editor_fg = "#CCCCCC",
  selection_bg = "#3333FF",
  selection_fg = "#FFFFFF",
  selection_inactive_bg = "#42424F",
  caret_row = "#000066",
  gutter_bg = "#131314",
  line_nr = "#999999",
  line_nr_active = "#FFFFFF",
  indent_guide = "#666666",
  separator = "#B3B3B3",
  line_separator = "#6A6173",
  border = "#E6E6E6",
  focus = "#1AEBFF",
  keyword = "#ED864A",
  string = "#54B33E",
  comment = "#7EC3E6",
  number = "#33CCFF",
  function_fg = "#FFCF40",
  constant = "#ED94FF",
  metadata = "#A9B837",
  doc_comment = "#499936",
  error = "#FA3232",
  warning = "#F58231",
  success = "#50A661",
  info = "#E0861F",
  tab_selected_bg = "#0E5D73",
  tab_hover_bg = "#0F6780",
  popup_bg = "#281A33",
  notification_bg = "#000080",
  informative_bg = "#450073",
  warning_bg = "#804605",
  error_bg = "#800002",
  modified = "#4FF0FF",
  cyan = "#37CCCC",
  magenta = "#FF96FF",
  link = "#D2F53C",
}

M.base_30 = {
  white = P.ui_fg,
  darker_black = P.ui_bg,
  black = P.editor_bg, -- nvim bg
  black2 = P.gutter_bg,
  one_bg = "#262626",
  one_bg2 = "#2B2B2B",
  one_bg3 = "#303030",
  grey = P.indent_guide,
  grey_fg = P.line_separator,
  grey_fg2 = P.line_nr,
  light_grey = P.separator,
  red = P.error,
  baby_pink = P.magenta,
  pink = P.constant,
  line = P.line_separator,
  green = P.string,
  vibrant_green = P.success,
  nord_blue = P.focus,
  blue = P.number,
  yellow = P.function_fg,
  sun = P.link,
  purple = P.informative_bg,
  dark_purple = P.error_bg,
  teal = P.modified,
  orange = P.keyword,
  cyan = P.cyan,
  statusline_bg = P.ui_bg,
  lightbg = P.tab_selected_bg,
  pmenu_bg = P.popup_bg,
  folder_bg = P.ui_fg,
  lavender = P.constant,
}

M.base_16 = {
  base00 = P.editor_bg,
  base01 = "#262626",
  base02 = P.selection_bg,
  base03 = P.line_separator,
  base04 = P.line_nr,
  base05 = P.editor_fg,
  base06 = P.border,
  base07 = P.ui_fg,
  base08 = P.error,
  base09 = P.info,
  base0A = P.function_fg,
  base0B = P.string,
  base0C = P.comment,
  base0D = P.number,
  base0E = P.keyword,
  base0F = P.metadata,
}

M.polish_hl = {
  defaults = {
    Normal = { fg = P.editor_fg, bg = P.editor_bg },
    NormalNC = { fg = P.editor_fg, bg = P.editor_bg },
    NormalFloat = { fg = P.ui_fg, bg = P.popup_bg },
    FloatBorder = { fg = P.border },
    FloatTitle = { fg = P.ui_fg, bg = P.popup_bg },
    Pmenu = { fg = P.ui_fg, bg = P.popup_bg },
    PmenuSel = { fg = P.selection_fg, bg = P.selection_bg },
    PmenuSbar = { bg = P.popup_bg },
    PmenuThumb = { bg = P.separator },
    CursorLine = { bg = P.caret_row },
    CursorColumn = { bg = P.caret_row },
    CursorLineNr = { fg = P.line_nr_active },
    LineNr = { fg = P.line_nr },
    Visual = { fg = P.selection_fg, bg = P.selection_bg },
    Search = { fg = P.selection_fg, bg = P.selection_bg },
    IncSearch = { fg = P.selection_fg, bg = P.selection_bg },
    WinSeparator = { fg = P.line_separator },
    SignColumn = { bg = P.gutter_bg },
    ColorColumn = { bg = P.gutter_bg },
  },
  nvimtree = {
    NvimTreeNormal = { bg = P.ui_bg, fg = P.ui_fg },
    NvimTreeNormalNC = { bg = P.ui_bg, fg = P.ui_fg },
    NvimTreeFolderName = { fg = P.ui_fg },
    NvimTreeOpenedFolderName = { fg = P.ui_fg, bold = true },
    NvimTreeRootFolder = { fg = P.ui_fg, bold = true },
    NvimTreeIndentMarker = { fg = P.line_separator },
    NvimTreeWinSeparator = { fg = P.line_separator },
  },
  syntax = {
    Comment = { fg = P.comment },
    String = { fg = P.string },
    Number = { fg = P.number, bold = true },
    Keyword = { fg = P.keyword },
    Function = { fg = P.function_fg },
    Type = { fg = P.ui_fg },
    Constant = { fg = P.constant },
    Identifier = { fg = P.ui_fg },
  },
  treesitter = {
    ["@comment"] = { fg = P.comment },
    ["@string"] = { fg = P.string },
    ["@number"] = { fg = P.number, bold = true },
    ["@float"] = { fg = P.number, bold = true },
    ["@keyword"] = { fg = P.keyword },
    ["@keyword.function"] = { fg = P.keyword },
    ["@function"] = { fg = P.function_fg },
    ["@function.call"] = { fg = P.function_fg },
    ["@method"] = { fg = P.function_fg },
    ["@method.call"] = { fg = P.function_fg },
    ["@type"] = { fg = P.ui_fg },
    ["@type.builtin"] = { fg = P.ui_fg },
    ["@constant"] = { fg = P.constant },
    ["@constant.builtin"] = { fg = P.constant },
    ["@property"] = { fg = P.constant },
    ["@variable"] = { fg = P.ui_fg },
    ["@variable.builtin"] = { fg = P.metadata },
    ["@parameter"] = { fg = P.ui_fg },
    ["@field"] = { fg = P.constant },
    ["@operator"] = { fg = P.keyword },
    ["@punctuation.delimiter"] = { fg = P.keyword },
    ["@punctuation.bracket"] = { fg = P.keyword },
    ["@tag"] = { fg = P.keyword },
    ["@tag.attribute"] = { fg = P.constant },
  },
}

M.type = "dark"

return M
