local M = {}

-- JetBrains Hacker (Specktro) palette reference for manual edits.
local P = {
  ui_bg = "#000000",
  ui_fg = "#FFFFFF",
  editor_bg = "#000000", -- force pure black editor background
  editor_fg = "#CCCCCC",
  selection_bg = "#3333FF",
  selection_fg = "#FFFFFF",
  selection_inactive_bg = "#42424F",
  caret_row = "#252525",
  breakpoint_line = "#401111",
  gutter_bg = "#131314",
  line_nr = "#999999",
  line_nr_active = "#FFFFFF",
  indent_guide = "#666666",
  separator = "#B3B3B3",
  line_separator = "#6A6173",
  border = "#E6E6E6",
  focus = "#1AEBFF",
  identifier = "#FFDE00",
  keyword = "#BC92FC",
  string = "#00FF00",
  comment = "#888888",
  number = "#33CCFF",
  builtin_function = "#8888C6",
  builtin_method = "#B200B2",
  named_param = "#AA4926",
  parameter = "#28E6FF",
  function_fg = "#FFCF40",
  constant = "#ED94FF",
  metadata = "#A9B837",
  decorator = "#E1FF00",
  doc_comment = "#499936",
  error = "#FA3232",
  warning = "#F58231",
  success = "#50A661",
  info = "#E0861F",
  tab_selected_bg = "#0E5D73",
  tab_hover_bg = "#0F6780",
  popup_bg = "#281A33",
  notification_bg = "#000080",
  informative_bg = "#450073",
  warning_bg = "#804605",
  error_bg = "#800002",
  modified = "#4FF0FF",
  cyan = "#37CCCC",
  magenta = "#FF96FF",
  link = "#D2F53C",
}

M.base_30 = {
  white = P.ui_fg,
  darker_black = P.ui_bg,
  black = P.editor_bg, -- nvim bg
  black2 = P.gutter_bg,
  one_bg = P.ui_bg,
  one_bg2 = P.ui_bg,
  one_bg3 = P.ui_bg,
  grey = P.indent_guide,
  grey_fg = P.line_separator,
  grey_fg2 = P.line_nr,
  light_grey = P.separator,
  red = P.error,
  baby_pink = P.magenta,
  pink = P.constant,
  line = P.line_separator,
  green = P.string,
  vibrant_green = P.success,
  nord_blue = P.focus,
  blue = P.number,
  yellow = P.function_fg,
  sun = P.link,
  purple = P.constant,
  dark_purple = P.error_bg,
  teal = P.modified,
  orange = P.keyword,
  cyan = P.cyan,
  statusline_bg = P.ui_bg,
  lightbg = P.tab_selected_bg,
  pmenu_bg = P.popup_bg,
  folder_bg = P.ui_fg,
  lavender = P.constant,
}

M.base_16 = {
  base00 = P.editor_bg,
  base01 = P.gutter_bg,
  base02 = P.selection_bg,
  base03 = P.line_separator,
  base04 = P.line_nr,
  base05 = P.editor_fg,
  base06 = P.border,
  base07 = P.ui_fg,
  base08 = P.error,
  base09 = P.info,
  base0A = P.function_fg,
  base0B = P.string,
  base0C = P.comment,
  base0D = P.number,
  base0E = P.keyword,
  base0F = P.constant,
}

M.polish_hl = {
  defaults = {
    Normal = { fg = P.editor_fg, bg = P.editor_bg },
    NormalNC = { fg = P.editor_fg, bg = P.editor_bg },
    NormalFloat = { fg = P.ui_fg, bg = P.popup_bg },
    FloatBorder = { fg = P.border },
    FloatTitle = { fg = P.ui_fg, bg = P.popup_bg },
    Pmenu = { fg = P.ui_fg, bg = P.popup_bg },
    PmenuSel = { fg = P.selection_fg, bg = P.selection_bg },
    PmenuSbar = { bg = P.popup_bg },
    PmenuThumb = { bg = P.separator },
    CursorLine = { bg = "#252525" },
    CursorColumn = { bg = "#252525" },
    CursorLineNr = { fg = P.line_nr_active, bg = "#252525" },
    LineNr = { fg = P.line_nr },
    Visual = { fg = P.selection_fg, bg = P.selection_bg },
    Search = { fg = P.selection_fg, bg = P.selection_bg },
    IncSearch = { fg = P.selection_fg, bg = P.selection_bg },
    WinSeparator = { fg = P.line_separator },
    SignColumn = { bg = P.gutter_bg },
    ColorColumn = { bg = P.editor_bg },
    VirtColumn = { fg = P.caret_row },
    TSField = { fg = P.constant },
    TSProperty = { fg = P.constant },
    TSVariableMember = { fg = P.constant },
    TSVariableMemberKey = { fg = P.constant },
    jsonKeyword = { fg = P.constant },
    DapBreakpointLine = { bg = P.breakpoint_line },
  },
  nvimtree = {
    NvimTreeNormal = { bg = P.ui_bg, fg = P.ui_fg },
    NvimTreeNormalNC = { bg = P.ui_bg, fg = P.ui_fg },
    NvimTreeFolderName = { fg = P.ui_fg },
    NvimTreeOpenedFolderName = { fg = P.ui_fg, bold = true },
    NvimTreeRootFolder = { fg = P.ui_fg, bold = true },
    NvimTreeFileName = { fg = P.string },
    NvimTreeOpenedFile = { fg = P.string, bold = true },
    NvimTreeSpecialFile = { fg = P.string },
    NvimTreeExecFile = { fg = P.string },
    NvimTreeSymlink = { fg = P.string },
    NvimTreeFileIcon = { fg = P.string },
    NvimTreeGitDirty = { fg = P.cyan },
    NvimTreeGitStaged = { fg = P.cyan },
    NvimTreeGitNew = { fg = P.cyan },
    NvimTreeGitRenamed = { fg = P.cyan },
    NvimTreeGitDeleted = { fg = P.cyan },
    NvimTreeGitMerge = { fg = P.cyan },
    NvimTreeGitIgnored = { fg = P.comment },
    NvimTreeIndentMarker = { fg = P.line_separator },
    NvimTreeWinSeparator = { fg = P.line_separator },
  },
  syntax = {
    Comment = { fg = P.comment },
    SpecialComment = { fg = P.doc_comment },
    DocComment = { fg = P.doc_comment },
    String = { fg = P.string },
    Character = { fg = P.string },
    Number = { fg = P.number, bold = true },
    Boolean = { fg = P.number, bold = true },
    Float = { fg = P.number, bold = true },
    Keyword = { fg = P.keyword },
    Conditional = { fg = P.keyword },
    Repeat = { fg = P.keyword },
    Statement = { fg = P.keyword },
    Exception = { fg = P.keyword },
    Operator = { fg = P.keyword },
    Function = { fg = P.function_fg },
    Identifier = { fg = P.identifier },
    Type = { fg = P.function_fg },
    Constant = { fg = P.constant, italic = true },
    Special = { fg = P.builtin_function },
    SpecialChar = { fg = P.builtin_function },
    PreProc = { fg = P.decorator },
    Include = { fg = P.keyword },
    Define = { fg = P.decorator },
    Macro = { fg = P.decorator },
    PreCondit = { fg = P.decorator },
    Label = { fg = P.keyword },
  },
  treesitter = {
    ["@comment"] = { fg = P.comment },
    ["@comment.line"] = { fg = P.comment },
    ["@comment.block"] = { fg = P.comment },
    ["@comment.documentation"] = { fg = P.doc_comment },
    ["@comment.doc"] = { fg = P.doc_comment },
    ["@string"] = { fg = P.string },
    ["@string.escape"] = { fg = P.keyword },
    ["@string.special"] = { fg = P.keyword },
    ["@character"] = { fg = P.string },
    ["@number"] = { fg = P.number, bold = true },
    ["@float"] = { fg = P.number, bold = true },
    ["@boolean"] = { fg = P.number, bold = true },
    ["@keyword"] = { fg = P.keyword },
    ["@keyword.conditional"] = { fg = P.keyword },
    ["@keyword.repeat"] = { fg = P.keyword },
    ["@keyword.return"] = { fg = P.keyword },
    ["@keyword.exception"] = { fg = P.keyword },
    ["@keyword.import"] = { fg = P.keyword },
    ["@keyword.function"] = { fg = P.keyword },
    ["@keyword.operator"] = { fg = P.keyword },
    ["@keyword.coroutine"] = { fg = P.keyword },
    ["@keyword.directive"] = { fg = P.keyword },
    ["@keyword.modifier"] = { fg = P.keyword },
    ["@keyword.storage"] = { fg = P.keyword },
    ["@include"] = { fg = P.keyword },
    ["@conditional"] = { fg = P.keyword },
    ["@repeat"] = { fg = P.keyword },
    ["@exception"] = { fg = P.keyword },
    ["@operator"] = { fg = P.keyword },
    ["@type"] = { fg = P.function_fg },
    ["@type.builtin"] = { fg = P.function_fg },
    ["@type.definition"] = { fg = P.function_fg },
    ["@type.interface"] = { fg = P.function_fg },
    ["@constructor"] = { fg = P.function_fg },
    ["@function"] = { fg = P.function_fg },
    ["@function.call"] = { fg = P.function_fg },
    ["@function.builtin"] = { fg = P.builtin_function },
    ["@function.method"] = { fg = P.function_fg },
    ["@method"] = { fg = P.function_fg },
    ["@method.call"] = { fg = P.function_fg },
    ["@method.builtin"] = { fg = P.builtin_method },
    ["@constructor.builtin"] = { fg = P.builtin_method },
    ["@field"] = { fg = P.constant },
    ["@property"] = { fg = P.constant },
    ["@variable.member"] = { fg = P.constant },
    ["@variable.member.key"] = { fg = P.constant },
    ["@constant"] = { fg = P.constant, italic = true },
    ["@constant.builtin"] = { fg = P.constant, italic = true },
    ["@constant.macro"] = { fg = P.constant, italic = true },
    ["@variable"] = { fg = P.identifier },
    ["@variable.builtin"] = { fg = P.metadata },
    ["@variable.parameter"] = { fg = P.parameter },
    ["@parameter"] = { fg = P.parameter },
    ["@parameter.name"] = { fg = P.named_param },
    ["@namespace"] = { fg = P.identifier },
    ["@module"] = { fg = P.identifier },
    ["@attribute"] = { fg = P.decorator },
    ["@attribute.builtin"] = { fg = P.decorator },
    ["@decorator"] = { fg = P.decorator },
    ["@decorator.function"] = { fg = P.decorator },
    ["@decorator.class"] = { fg = P.decorator },
    ["@punctuation.delimiter"] = { fg = P.keyword, bold = true },
    ["@punctuation.bracket"] = { fg = P.keyword, bold = true },
    ["@tag"] = { fg = P.keyword },
    ["@tag.attribute"] = { fg = P.constant },
  },
}

M.type = "dark"

return M
